export const StoreConstants = {
    SET_CURRENT_USER_GEOLOCATION: "SET_CURRENT_USER_GEOLOCATION",
    UNSET_CURRENT_USER_GEOLOCATION: "UNSET_CURRENT_USER_GEOLOCATION",

    SET_SELECTED_LOCATION: "SET_SELECTED_LOCATION",
    UNSET_SELECTED_LOCATION: "UNSET_SELECTED_LOCATION",

    ADD_TO_WARNING_LIST: "ADD_TO_WARNING_LIST",
    UNSET_WARNING_LIST: "UNSET_WARNING_LIST",

    ADD_TO_ERROR_LIST: "ADD_TO_ERROR_LIST",
    UNSET_ERROR_LIST: "UNSET_ERROR_LIST"
}
