const OWM_API_KEY_STR = "OWM_API_KEY"
const DEFAULT_UNITS_STR = "DEFAULT_UNITS"
const THEME_SETTING_STR = "THEME_SETTING"
const DISPLAY_UNIT_METHOD_STR = "DISPLAY_UNIT_METHOD"

const baseAPIURL = "https://api.openweathermap.org/"
const GOOGLE_MAPS_API_KEY = ""

export {
    OWM_API_KEY_STR,
    DEFAULT_UNITS_STR,
    baseAPIURL,
    THEME_SETTING_STR,
    DISPLAY_UNIT_METHOD_STR,
    GOOGLE_MAPS_API_KEY
}
